const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');const {corrigirCaso26216,executar}=require('./functions/retrabalhos');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1280,390]){
const base={usuarios:{},ops:{'26160-04':{lote:'26160/04',abertaLinha:'Linha 2',produzido:0,produzidoLinha:0},'26216-04':{lote:'26216/04',status:'Concluído',produzidoLinha:867,sku:'PRF',skuPedidoKey:'0017__PRF',produto:'PERFUME TAWUS 30ML',cliente:'AFEER'}},estado_linhas:{Linha_2:{lote:'26160/04',status:'parada'}},pedidos:{'0007__DPHNPC01':{produzido:0}}};corrigirCaso26216(base,'2026-09-22T00:00:00Z');base.usuarios.ui={role:'admin',nome:'Admin teste'};
const page=await browser.newPage({viewport:{width,height:950},timezoneId:'America/Sao_Paulo'});page.on('dialog',d=>d.accept());const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.exposeFunction('__call',data=>{executar(base,data,'ui',new Date().toISOString());return structuredClone(base.retrabalhos);});
const html=fs.readFileSync('public/form.html','utf8'),style=html.match(/<style>([\s\S]*?)<\/style>/)[1];
await page.setContent('<style>'+style+'</style><section id="secaoTurnoLinhas"><div id="grid"></div></section><form id="prodForm"><input id="fLinha" value="Linha 2"></form>');
await page.evaluate(({rt,states})=>{window.currentUser={role:'admin'};window.latestAndonStates=states;window.sanitizeKey=s=>s.replace(/ /g,'_');window.db={ref:p=>p};window.dbOnValue=(r,cb)=>{window.__listener=cb;cb({val:()=>rt});};window.showSuccess=(a,b)=>window.__success=a;window.firebase={functions:()=>({httpsCallable:()=>async d=>{if(window.__fail)throw new Error('Sem conexão');const r=await window.__call(d);window.__listener({val:()=>r});return {data:{ok:true}};}})};window.__submitted=0;document.getElementById('prodForm').addEventListener('submit',e=>{e.preventDefault();window.__submitted++;});}, {rt:base.retrabalhos,states:base.estado_linhas});
await page.addScriptTag({content:fs.readFileSync('public/shared/retrabalhos-gestao.js','utf8')});await page.addScriptTag({content:fs.readFileSync('public/shared/retrabalhos-tela.js','utf8')});await page.evaluate(()=>document.dispatchEvent(new Event('DOMContentLoaded')));
await page.evaluate(()=>document.getElementById('grid').appendChild(RetrabalhosTela.card('Linha 2',latestAndonStates.Linha_2)));
assert.match(await page.locator('#grid').innerText(),/Retrabalho · OP 26216\/04/);assert.match(await page.locator('#grid').innerText(),/17:09/);
await page.getByText('Ver retrabalho / apontamentos',{exact:true}).click();assert.equal(await page.locator('#rtQuantidade').inputValue(),'');assert.match(await page.locator('#rtApontamentos').innerText(),/Quantidade pendente/);assert.match(await page.locator('#retrabalhoModal').innerText(),/Sedimentação/);
/* MUDANÇA DE COMPORTAMENTO (Claude, 22/09, a pedido do usuário): antes o botão de encerrar NÃO era renderizado quando havia quantidade pendente. Sumir em silêncio fazia parecer defeito -- agora ele aparece DESABILITADO, com o motivo escrito ao lado. */
const btnFim=page.getByText('Encerrar execução — aguardar Qualidade',{exact:true});assert.equal(await btnFim.count(),1,'o botão existe');assert.equal(await btnFim.isDisabled(),true,'mas travado enquanto houver pendência');assert.match(await page.locator('#retrabalhoModal').innerText(),/Falta conferir a quantidade/,'e a tela diz por quê');
await page.getByText('Salvar quantidade conferida',{exact:true}).click();assert.match(await page.locator('#rtErro').innerText(),/Informe a quantidade/);
await page.locator('#rtQuantidade').fill('321');await page.evaluate(()=>window.__fail=true);await page.getByText('Salvar quantidade conferida',{exact:true}).click();assert.match(await page.locator('#rtErro').innerText(),/Sem conexão/);await page.evaluate(()=>window.__fail=false);
if(width===390)await page.screenshot({path:'scratch/retrabalho-celular.png',fullPage:true});
await page.getByText('Salvar quantidade conferida',{exact:true}).click();await page.waitForFunction(()=>window.__success);assert.equal(base.retrabalhos['RT-26216-04-20260921'].quantidadeConfirmada,321);assert.equal(base.ops['26216-04'].produzidoLinha,867);
await page.evaluate(()=>document.getElementById('prodForm').requestSubmit());assert.equal(await page.evaluate(()=>__submitted),0);
await page.evaluate(()=>{currentUser.role='production';RetrabalhosTela.abrir('RT-26216-04-20260921');});assert.equal(await page.locator('#rtQuantidade').count(),0);assert.equal(await page.getByText('Retomar retrabalho agora',{exact:true}).count(),1);assert.deepEqual(errors,[]);await page.close();}
console.log('OK UI: desktop/celular, horários e motivo, pendência sem zero fictício, edição administrativa, falha/retry, bloqueio de apontamento comum e produção original preservada.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
